# The `Rope` class and related methods were generated by ChatGPT outside of contests.
# Chunked implicit-treap Rope for PyPy / CPython.
#
# Main costs (B = BLOCK, M = number of chunks):
#   a[k], a[k] = x              : expected O(log M)
#   insert / pop                 : expected O(log M + B)
#   erase / reverse / cut        : expected O(log M + B) at boundaries
#   insert_many                  : expected O(log M + len(values))
#   iteration / tolist / copy    : O(n)
#
# `concat(other)` is destructive: it consumes `other` in order to stay cheap.

BLOCK = 512
MAX_BLOCK = 1024
_MASK32 = 0xFFFFFFFF
_rng_state = 2463534242


def _next_prio():
    # xorshift32: fast, deterministic, and no random-module overhead.
    global _rng_state
    x = _rng_state
    x ^= (x << 13) & _MASK32
    x ^= x >> 17
    x ^= (x << 5) & _MASK32
    x &= _MASK32
    _rng_state = x
    return x


class _Node:
    __slots__ = ("a", "l", "r", "prio", "size", "rev")

    def __init__(self, a):
        self.a = a
        self.l = None
        self.r = None
        self.prio = _next_prio()
        self.size = len(a)
        self.rev = False


def _size(t):
    return 0 if t is None else t.size


def _update(t):
    t.size = _size(t.l) + len(t.a) + _size(t.r)


def _toggle_reverse(t):
    if t is not None:
        t.rev = not t.rev


def _push(t):
    if t is not None and t.rev:
        t.rev = False
        t.l, t.r = t.r, t.l
        t.a.reverse()
        _toggle_reverse(t.l)
        _toggle_reverse(t.r)


def _merge_plain(a, b):
    """Treap merge without boundary-block coalescing."""
    if a is None:
        return b
    if b is None:
        return a

    if a.prio > b.prio:
        _push(a)
        a.r = _merge_plain(a.r, b)
        _update(a)
        return a

    _push(b)
    b.l = _merge_plain(a, b.l)
    _update(b)
    return b


def _peek_right(t):
    while True:
        _push(t)
        if t.r is None:
            return t
        t = t.r


def _peek_left(t):
    while True:
        _push(t)
        if t.l is None:
            return t
        t = t.l


def _pop_right_node(t):
    _push(t)
    if t.r is None:
        rest = t.l
        t.l = None
        _update(t)
        return rest, t

    t.r, node = _pop_right_node(t.r)
    _update(t)
    return t, node


def _pop_left_node(t):
    _push(t)
    if t.l is None:
        rest = t.r
        t.r = None
        _update(t)
        return rest, t

    t.l, node = _pop_left_node(t.l)
    _update(t)
    return t, node


def _concat_roots(a, b):
    """Merge two sequences and opportunistically join their edge blocks."""
    if a is None:
        return b
    if b is None:
        return a

    ra = _peek_right(a)
    lb = _peek_left(b)
    if len(ra.a) + len(lb.a) <= MAX_BLOCK:
        a, ra = _pop_right_node(a)
        b, lb = _pop_left_node(b)
        ra.a.extend(lb.a)
        _update(ra)
        return _merge_plain(_merge_plain(a, ra), b)

    return _merge_plain(a, b)


def _split(t, k):
    """Split into first k elements and the rest. 0 <= k <= size(t)."""
    if t is None:
        return None, None

    _push(t)
    ls = _size(t.l)
    m = len(t.a)

    if k < ls:
        a, b = _split(t.l, k)
        t.l = b
        _update(t)
        return a, t

    if k > ls + m:
        a, b = _split(t.r, k - ls - m)
        t.r = a
        _update(t)
        return t, b

    if k == ls:
        a = t.l
        t.l = None
        _update(t)
        return a, t

    if k == ls + m:
        b = t.r
        t.r = None
        _update(t)
        return t, b

    # k lies strictly inside this chunk.
    off = k - ls
    left_sub = t.l
    right_sub = t.r
    t.l = t.r = None

    right_node = _Node(t.a[off:])
    t.a = t.a[:off]
    _update(t)

    return _merge_plain(left_sub, t), _merge_plain(right_node, right_sub)


def _split_oversized_node(t):
    """Split t.a after a local insertion made it too large."""
    left_sub = t.l
    right_sub = t.r
    t.l = t.r = None

    m = len(t.a) // 2
    right_node = _Node(t.a[m:])
    t.a = t.a[:m]
    _update(t)

    return _merge_plain(
        _merge_plain(left_sub, t),
        _merge_plain(right_node, right_sub),
    )


def _insert(t, k, x):
    _push(t)
    ls = _size(t.l)
    m = len(t.a)

    if k < ls:
        t.l = _insert(t.l, k, x)
    elif k <= ls + m:
        t.a.insert(k - ls, x)
    else:
        t.r = _insert(t.r, k - ls - m, x)

    _update(t)
    if len(t.a) > MAX_BLOCK:
        return _split_oversized_node(t)
    return t


def _pop_at(t, k):
    _push(t)
    ls = _size(t.l)
    m = len(t.a)

    if k < ls:
        t.l, x = _pop_at(t.l, k)
        _update(t)
        return t, x

    if k >= ls + m:
        t.r, x = _pop_at(t.r, k - ls - m)
        _update(t)
        return t, x

    x = t.a.pop(k - ls)
    if t.a:
        _update(t)
        return t, x

    return _concat_roots(t.l, t.r), x


def _get_node(t, k):
    while True:
        _push(t)
        ls = _size(t.l)
        m = len(t.a)

        if k < ls:
            t = t.l
        elif k < ls + m:
            return t, k - ls
        else:
            k -= ls + m
            t = t.r


def _collect_range(t, l, r, out):
    """Append logical sequence [l:r] in this subtree to out."""
    if t is None or l >= r:
        return

    _push(t)
    ls = _size(t.l)
    m = len(t.a)

    if l < ls:
        _collect_range(t.l, l, min(r, ls), out)

    lo = max(0, l - ls)
    hi = min(m, r - ls)
    if lo < hi:
        out.extend(t.a[lo:hi])

    if r > ls + m:
        _collect_range(
            t.r,
            max(0, l - ls - m),
            r - ls - m,
            out,
        )


def _build_root(data):
    root = None
    n = len(data)
    for i in range(0, n, BLOCK):
        root = _merge_plain(root, _Node(data[i : i + BLOCK]))
    return root


class Rope:
    """Mutable sequence backed by a chunked implicit treap."""

    __slots__ = ("root",)

    def __init__(self, iterable=()):
        self.root = _build_root(list(iterable))

    @classmethod
    def _from_root(cls, root):
        obj = cls.__new__(cls)
        obj.root = root
        return obj

    @staticmethod
    def _normalize_index(k, n):
        if k < 0:
            k += n
        if k < 0 or k >= n:
            raise IndexError("rope index out of range")
        return k

    @staticmethod
    def _normalize_insert_index(k, n):
        # Match list.insert: negative indices and oversized indices are clamped.
        if k < 0:
            k += n
            if k < 0:
                k = 0
        elif k > n:
            k = n
        return k

    @staticmethod
    def _normalize_range(l, r, n):
        if r is None:
            r = n
        l, r, _ = slice(l, r, 1).indices(n)
        if r < l:
            r = l
        return l, r

    def __len__(self):
        return _size(self.root)

    def __bool__(self):
        return self.root is not None

    def __getitem__(self, key):
        n = len(self)
        if isinstance(key, slice):
            start, stop, step = key.indices(n)
            if step == 1:
                out = []
                _collect_range(self.root, start, stop, out)
                return out
            return self.tolist()[key]

        k = self._normalize_index(key, n)
        node, i = _get_node(self.root, k)
        return node.a[i]

    def __setitem__(self, key, value):
        n = len(self)
        if isinstance(key, slice):
            start, stop, step = key.indices(n)

            if step != 1:
                # Rare path; preserve exact Python-list semantics.
                data = self.tolist()
                data[key] = value
                self.root = _build_root(data)
                return

            values = list(value)
            a, bc = _split(self.root, start)
            _, c = _split(bc, stop - start)
            mid = _build_root(values)
            self.root = _concat_roots(_concat_roots(a, mid), c)
            return

        k = self._normalize_index(key, n)
        node, i = _get_node(self.root, k)
        node.a[i] = value

    def __delitem__(self, key):
        if isinstance(key, slice):
            n = len(self)
            start, stop, step = key.indices(n)
            if step == 1:
                self.erase(start, stop)
            else:
                # Rare path; rebuilding is cleaner and usually faster than
                # deleting many scattered positions one by one.
                data = self.tolist()
                del data[key]
                self.root = _build_root(data)
            return

        self.pop(key)

    def insert(self, k, x):
        n = len(self)
        k = self._normalize_insert_index(k, n)

        if self.root is None:
            self.root = _Node([x])
        else:
            self.root = _insert(self.root, k, x)

    def append(self, x):
        self.insert(len(self), x)

    def extend(self, iterable):
        data = list(iterable)
        if data:
            self.root = _concat_roots(self.root, _build_root(data))

    def insert_many(self, k, iterable):
        data = list(iterable)
        if not data:
            return

        k = self._normalize_insert_index(k, len(self))
        a, b = _split(self.root, k)
        mid = _build_root(data)
        self.root = _concat_roots(_concat_roots(a, mid), b)

    def pop(self, k=-1):
        n = len(self)
        if n == 0:
            raise IndexError("pop from empty rope")

        k = self._normalize_index(k, n)
        self.root, x = _pop_at(self.root, k)
        return x

    def erase(self, l, r=None):
        """Delete one element at l, or the half-open range [l, r)."""
        if r is None:
            self.pop(l)
            return

        l, r = self._normalize_range(l, r, len(self))
        if l >= r:
            return

        a, bc = _split(self.root, l)
        _, c = _split(bc, r - l)
        self.root = _concat_roots(a, c)

    def reverse(self, l=0, r=None):
        """Reverse the half-open range [l, r); default is the whole rope."""
        n = len(self)
        l, r = self._normalize_range(l, r, n)
        if r - l <= 1:
            return

        if l == 0 and r == n:
            _toggle_reverse(self.root)
            return

        a, bc = _split(self.root, l)
        mid, c = _split(bc, r - l)
        _toggle_reverse(mid)
        self.root = _concat_roots(_concat_roots(a, mid), c)

    def split(self, k):
        """Keep [:k] in self and return [k:] as a new Rope."""
        k = self._normalize_insert_index(k, len(self))
        a, b = _split(self.root, k)
        self.root = a
        return Rope._from_root(b)

    def concat(self, other):
        """Append another Rope in O(log M)-ish time and consume `other`."""
        if not isinstance(other, Rope):
            raise TypeError("can only concatenate Rope")
        if other is self:
            raise ValueError("cannot concatenate Rope with itself")

        self.root = _concat_roots(self.root, other.root)
        other.root = None
        return self

    def cut(self, l, r=None):
        """Remove [l:r] from self and return it as a Rope without copying."""
        l, r = self._normalize_range(l, r, len(self))
        if l >= r:
            return Rope()

        a, bc = _split(self.root, l)
        mid, c = _split(bc, r - l)
        self.root = _concat_roots(a, c)
        return Rope._from_root(mid)

    def clear(self):
        self.root = None

    def __iter__(self):
        stack = []
        t = self.root

        while stack or t is not None:
            while t is not None:
                _push(t)
                stack.append(t)
                t = t.l

            t = stack.pop()
            yield from t.a
            t = t.r

    def __reversed__(self):
        stack = []
        t = self.root

        while stack or t is not None:
            while t is not None:
                _push(t)
                stack.append(t)
                t = t.r

            t = stack.pop()
            yield from reversed(t.a)
            t = t.l

    def tolist(self):
        return list(self)

    def copy(self):
        return Rope(self)

    def __repr__(self):
        return "Rope(" + repr(self.tolist()) + ")"
