# Generated by ChatGPT (OpenAI) outside of contests.
# Chunked implicit-treap Rope for Codon.
#
# This version preserves the PyPy version's public functionality while
# avoiding Python features that are awkward for Codon's static type system.
# In particular:
#   - recursive node fields are explicitly typed;
#   - @classmethod / __new__ construction is not used;
#   - __slots__ is not used;
#   - Rope and _Node are generic Codon classes.
#
# Main costs (B = BLOCK, M = number of chunks):
#   a[k], a[k] = x              : expected O(log M)
#   insert / pop                 : expected O(log M + B)
#   erase / reverse / cut        : expected O(log M + B) at boundaries
#   insert_many                  : expected O(log M + len(values))
#   iteration / tolist / copy    : O(n)
#
# `concat(other)` is destructive: it consumes `other` in order to stay cheap.

# ABC392-FでAC可能なことを確認

from typing import Optional

BLOCK = 512
MAX_BLOCK = 1024
_MASK32 = 0xFFFFFFFF
_rng_state = 2463534242


def _next_prio() -> int:
    # xorshift32: fast, deterministic, and no random-module overhead.
    global _rng_state
    x = _rng_state
    x ^= (x << 13) & _MASK32
    x ^= x >> 17
    x ^= (x << 5) & _MASK32
    x &= _MASK32
    _rng_state = x
    return x


class _Node[T]:
    a: list[T]
    l: Optional[_Node[T]]
    r: Optional[_Node[T]]
    prio: int
    size: int
    rev: bool

    def __init__(self, a: list[T]):
        self.a = a
        self.l = None
        self.r = None
        self.prio = _next_prio()
        self.size = len(a)
        self.rev = False


def _size[T](t: Optional[_Node[T]]) -> int:
    return 0 if t is None else t.size


def _update[T](t: _Node[T]):
    t.size = _size(t.l) + len(t.a) + _size(t.r)


def _toggle_reverse[T](t: Optional[_Node[T]]):
    if t is not None:
        t.rev = not t.rev


def _push[T](t: Optional[_Node[T]]):
    if t is not None and t.rev:
        t.rev = False
        t.l, t.r = t.r, t.l
        t.a.reverse()
        _toggle_reverse(t.l)
        _toggle_reverse(t.r)


def _merge_plain[T](a: Optional[_Node[T]], b: Optional[_Node[T]]) -> Optional[_Node[T]]:
    if a is None:
        return b
    if b is None:
        return a

    if a.prio > b.prio:
        _push(a)
        a.r = _merge_plain(a.r, b)
        _update(a)
        return a

    _push(b)
    b.l = _merge_plain(a, b.l)
    _update(b)
    return b


def _peek_right[T](t: _Node[T]) -> _Node[T]:
    while True:
        _push(t)
        if t.r is None:
            return t
        t = t.r


def _peek_left[T](t: _Node[T]) -> _Node[T]:
    while True:
        _push(t)
        if t.l is None:
            return t
        t = t.l


def _pop_right_node[T](t: _Node[T]):
    _push(t)
    if t.r is None:
        rest = t.l
        t.l = None
        _update(t)
        return rest, t

    t.r, node = _pop_right_node(t.r)
    _update(t)
    return t, node


def _pop_left_node[T](t: _Node[T]):
    _push(t)
    if t.l is None:
        rest = t.r
        t.r = None
        _update(t)
        return rest, t

    t.l, node = _pop_left_node(t.l)
    _update(t)
    return t, node


def _concat_roots[T](
    a: Optional[_Node[T]], b: Optional[_Node[T]]
) -> Optional[_Node[T]]:
    """Merge two sequences and opportunistically join their edge blocks."""
    if a is None:
        return b
    if b is None:
        return a

    ra = _peek_right(a)
    lb = _peek_left(b)
    if len(ra.a) + len(lb.a) <= MAX_BLOCK:
        a, ra = _pop_right_node(a)
        b, lb = _pop_left_node(b)
        ra.a.extend(lb.a)
        _update(ra)
        return _merge_plain(_merge_plain(a, ra), b)

    return _merge_plain(a, b)


def _split[T](t: Optional[_Node[T]], k: int):
    """Split into first k elements and the rest. 0 <= k <= size(t)."""
    if t is None:
        return None, None

    _push(t)
    ls = _size(t.l)
    m = len(t.a)

    if k < ls:
        a, b = _split(t.l, k)
        t.l = b
        _update(t)
        return a, t

    if k > ls + m:
        a, b = _split(t.r, k - ls - m)
        t.r = a
        _update(t)
        return t, b

    if k == ls:
        a = t.l
        t.l = None
        _update(t)
        return a, t

    if k == ls + m:
        b = t.r
        t.r = None
        _update(t)
        return t, b

    off = k - ls
    left_sub = t.l
    right_sub = t.r
    t.l = None
    t.r = None

    right_node = _Node(t.a[off:])
    t.a = t.a[:off]
    _update(t)

    return _merge_plain(left_sub, t), _merge_plain(right_node, right_sub)


def _split_oversized_node[T](t: _Node[T]) -> Optional[_Node[T]]:
    left_sub = t.l
    right_sub = t.r
    t.l = None
    t.r = None

    m = len(t.a) // 2
    right_node = _Node(t.a[m:])
    t.a = t.a[:m]
    _update(t)

    return _merge_plain(
        _merge_plain(left_sub, t),
        _merge_plain(right_node, right_sub),
    )


def _insert[T](t: _Node[T], k: int, x: T) -> Optional[_Node[T]]:
    _push(t)
    ls = _size(t.l)
    m = len(t.a)

    if k < ls:
        t.l = _insert(t.l, k, x)
    elif k <= ls + m:
        t.a.insert(k - ls, x)
    else:
        t.r = _insert(t.r, k - ls - m, x)

    _update(t)
    if len(t.a) > MAX_BLOCK:
        return _split_oversized_node(t)
    return t


def _pop_at[T](t: _Node[T], k: int):
    _push(t)
    ls = _size(t.l)
    m = len(t.a)

    if k < ls:
        t.l, x = _pop_at(t.l, k)
        _update(t)
        return t, x

    if k >= ls + m:
        t.r, x = _pop_at(t.r, k - ls - m)
        _update(t)
        return t, x

    x = t.a.pop(k - ls)
    if t.a:
        _update(t)
        return t, x

    return _concat_roots(t.l, t.r), x


def _get_node[T](t: _Node[T], k: int):
    while True:
        _push(t)
        ls = _size(t.l)
        m = len(t.a)

        if k < ls:
            t = t.l
        elif k < ls + m:
            return t, k - ls
        else:
            k -= ls + m
            t = t.r


def _collect_range[T](t: Optional[_Node[T]], l: int, r: int, out: list[T]):
    if t is None or l >= r:
        return

    _push(t)
    ls = _size(t.l)
    m = len(t.a)

    if l < ls:
        _collect_range(t.l, l, min(r, ls), out)

    lo = max(0, l - ls)
    hi = min(m, r - ls)
    if lo < hi:
        out.extend(t.a[lo:hi])

    if r > ls + m:
        _collect_range(
            t.r,
            max(0, l - ls - m),
            r - ls - m,
            out,
        )


def _build_root[T](data: list[T]) -> Optional[_Node[T]]:
    root: Optional[_Node[T]] = None
    n = len(data)
    for i in range(0, n, BLOCK):
        root = _merge_plain(root, _Node(data[i : i + BLOCK]))
    return root


class Rope[T]:
    """Mutable sequence backed by a chunked implicit treap."""

    root: Optional[_Node[T]]

    def __init__(self, iterable=()):
        self.root = _build_root(list(iterable))

    def _new_from_root(self, root: Optional[_Node[T]]):
        # Codon-friendly replacement for the PyPy version's @classmethod
        # _from_root().  The current Rope fixes T, so the new Rope has the
        # same element type without needing dynamic class construction.
        obj = Rope[T]()
        obj.root = root
        return obj

    @staticmethod
    def _normalize_index(k: int, n: int) -> int:
        if k < 0:
            k += n
        if k < 0 or k >= n:
            raise IndexError("rope index out of range")
        return k

    @staticmethod
    def _normalize_insert_index(k: int, n: int) -> int:
        if k < 0:
            k += n
            if k < 0:
                k = 0
        elif k > n:
            k = n
        return k

    @staticmethod
    def _normalize_range(l: int, r: Optional[int], n: int):
        if r is None:
            r = n
        l, r, _ = slice(l, r, 1).indices(n)
        if r < l:
            r = l
        return l, r

    def __len__(self) -> int:
        return _size(self.root)

    def __bool__(self) -> bool:
        return self.root is not None

    def __getitem__(self, key):
        n = len(self)
        if isinstance(key, slice):
            start, stop, step = key.indices(n)
            if step == 1:
                out: list[T] = []
                _collect_range(self.root, start, stop, out)
                return out
            return self.tolist()[key]

        k = self._normalize_index(key, n)
        node, i = _get_node(self.root, k)
        return node.a[i]

    def __setitem__(self, key, value):
        n = len(self)
        if isinstance(key, slice):
            start, stop, step = key.indices(n)

            if step != 1:
                data = self.tolist()
                data[key] = value
                self.root = _build_root(data)
                return

            values = list(value)
            a, bc = _split(self.root, start)
            _, c = _split(bc, stop - start)
            mid = _build_root(values)
            self.root = _concat_roots(_concat_roots(a, mid), c)
            return

        k = self._normalize_index(key, n)
        node, i = _get_node(self.root, k)
        node.a[i] = value

    def __delitem__(self, key):
        if isinstance(key, slice):
            n = len(self)
            start, stop, step = key.indices(n)
            if step == 1:
                self.erase(start, stop)
            else:
                data = self.tolist()
                del data[key]
                self.root = _build_root(data)
            return

        self.pop(key)

    def insert(self, k: int, x: T):
        n = len(self)
        k = self._normalize_insert_index(k, n)

        if self.root is None:
            self.root = _Node([x])
        else:
            self.root = _insert(self.root, k, x)

    def append(self, x: T):
        self.insert(len(self), x)

    def extend(self, iterable):
        data = list(iterable)
        if data:
            self.root = _concat_roots(self.root, _build_root(data))

    def insert_many(self, k: int, iterable):
        data = list(iterable)
        if not data:
            return

        k = self._normalize_insert_index(k, len(self))
        a, b = _split(self.root, k)
        mid = _build_root(data)
        self.root = _concat_roots(_concat_roots(a, mid), b)

    def pop(self, k: int = -1):
        n = len(self)
        if n == 0:
            raise IndexError("pop from empty rope")

        k = self._normalize_index(k, n)
        self.root, x = _pop_at(self.root, k)
        return x

    def erase(self, l: int, r: Optional[int] = None):
        if r is None:
            self.pop(l)
            return

        l, r = self._normalize_range(l, r, len(self))
        if l >= r:
            return

        a, bc = _split(self.root, l)
        _, c = _split(bc, r - l)
        self.root = _concat_roots(a, c)

    def reverse(self, l: int = 0, r: Optional[int] = None):
        n = len(self)
        l, r = self._normalize_range(l, r, n)
        if r - l <= 1:
            return

        if l == 0 and r == n:
            _toggle_reverse(self.root)
            return

        a, bc = _split(self.root, l)
        mid, c = _split(bc, r - l)
        _toggle_reverse(mid)
        self.root = _concat_roots(_concat_roots(a, mid), c)

    def split(self, k: int):
        k = self._normalize_insert_index(k, len(self))
        a, b = _split(self.root, k)
        self.root = a
        return self._new_from_root(b)

    def concat(self, other: Rope[T]):
        if other is self:
            raise ValueError("cannot concatenate Rope with itself")

        self.root = _concat_roots(self.root, other.root)
        other.root = None
        return self

    def cut(self, l: int, r: Optional[int] = None):
        l, r = self._normalize_range(l, r, len(self))
        if l >= r:
            return self._new_from_root(None)

        a, bc = _split(self.root, l)
        mid, c = _split(bc, r - l)
        self.root = _concat_roots(a, c)
        return self._new_from_root(mid)

    def clear(self):
        self.root = None

    def __iter__(self):
        stack: list[_Node[T]] = []
        t = self.root

        while stack or t is not None:
            while t is not None:
                _push(t)
                stack.append(t)
                t = t.l

            t = stack.pop()
            for x in t.a:
                yield x
            t = t.r

    def __reversed__(self):
        stack: list[_Node[T]] = []
        t = self.root

        while stack or t is not None:
            while t is not None:
                _push(t)
                stack.append(t)
                t = t.r

            t = stack.pop()
            for i in range(len(t.a) - 1, -1, -1):
                yield t.a[i]
            t = t.l

    def tolist(self) -> list[T]:
        return list(self)

    def copy(self):
        return Rope[T](self)

    def __repr__(self) -> str:
        return "Rope(" + repr(self.tolist()) + ")"
